title: Spiderum
email: team@spiderum.com
description: >- # this means to ignore newlines until "baseurl:"
    Viết nhiều vô ku
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
    # - jekyll-feed
    - jekyll-seo-tag

sass:
    style: compressed
