basic_settings:
    site_title: Spiderum
    site_description: Viết nhiều vô ku

categories:
    - title: 'Thông báo - Cập nhật'
      image: 'https://spiderum.com/assets/images/categories/composition.jpg'
    - title: 'Quan điểm - Tranh luận'
      image: 'https://spiderum.com/assets/images/categories/business-min.jpg'
    - title: 'Truyền cảm hứng'
      image: 'https://spiderum.com/assets/images/categories/inspirational-min.jpg'
    - title: 'Khoa học - Công nghệ'
      image: 'https://spiderum.com/assets/images/categories/laptop-min.jpg'
    - title: 'Chuyện trò - Tâm sự'
      image: 'https://spiderum.com/assets/images/categories/conversation-min.jpg'
    - title: 'Science2vn'
      image: 'https://spiderum.com/assets/images/categories/universe-min.jpg'
    - title: 'Thể thao'
      image: 'https://spiderum.com/assets/images/categories/sport-min.jpg'
    - title: 'Game'
      image: 'https://spiderum.com/assets/images/categories/game-min.jpg'
    - title: 'Sự kiện Spiderum'
      image: 'https://spiderum.com/assets/images/categories/event-min.jpg'
    - title: 'Otakulture'
      image: 'https://spiderum.com/assets/images/categories/otakulture.jpg'
    - title: 'Sáng tác'
      image: 'https://spiderum.com/assets/images/categories/composition.jpg'
    - title: 'Comics'
      image: 'https://spiderum.com/assets/images/categories/comics-min.jpg'
    - title: 'Phim'
      image: 'https://spiderum.com/assets/images/categories/film-min.jpg'
    - title: 'Sách'
      image: 'https://spiderum.com/assets/images/categories/books-min.jpg'
    - title: 'Du lịch - Ẩm thực'
      image: 'https://spiderum.com/assets/images/categories/entertainment-min.jpg'
    - title: 'Kỹ năng'
      image: 'https://spiderum.com/assets/images/categories/work-min.jpg'
    - title: 'Âm nhạc'
      image: 'https://spiderum.com/assets/images/categories/music.jpg'
    - title: 'English Zone'
      image: 'https://spiderum.com/assets/images/categories/english-min.jpg'
